### ISSUE TITLE
image cannot display

### ISSUE THREAD

**Issue by johnzyx** [valnub/Framework7-with-AngularJS-demo-app#5]
Hi  Timo Ernst,
I am using the"Framework7-with-AngularJS-demo-app" to do excise for Framework7 + angularJS.

When I tried the app on Android emulator, the image cannot display. But the image URL is correct when opening in a new Tag of browse
![issue](https://cloud.githubusercontent.com/assets/23569565/21994019/a3f5b214-dc58-11e6-8bc7-aed71d574a92.png)

 This problem also happen when I tried it in my mobile phone.

Can you kindly give me some tips? I have spent a night to work for it however still does not work. 

THX

​

**Comment by valnub** [comment]
Hi, check out the source of my live demo https://www.timo-ernst.net/misc/f7-angular-screencast-demo/ <https://www.timo-ernst.net/misc/f7-angular-screencast-demo/>

The HTML tag and its attributes look different to yours:

<img ng-src="http://resizing.flixster.com/2pEmb9X8xxhFUTfWpL_GuZXajPE=/54x80/dkpu1ddg7pbsk.cloudfront.net/movie/11/19/07/11190716_ori.jpg" width="80" src="http://resizing.flixster.com/2pEmb9X8xxhFUTfWpL_GuZXajPE=/54x80/dkpu1ddg7pbsk.cloudfront.net/movie/11/19/07/11190716_ori.jpg“>

Some things I noticed in your code:

- You’re serving from file:/// - try with http instead
- There is a String ?aa-2323 at the end of the img url. What is that? can you remove it?
- You should use ng-src instead of src: https://docs.angularjs.org/api/ng/directive/ngSrc <https://docs.angularjs.org/api/ng/directive/ngSrc>

Cheers,
Timo
