### ISSUE TITLE
Navigation to new view

### ISSUE THREAD

**Issue by nutanlade** [valnub/Framework7-with-AngularJS-demo-app#6]
@valnub Can you please provide one example or update template to navigate from controller. After login user should be redirect to another page.

**Comment by valnub** [comment]
Hi, just call from your controller:

`yourView.router.load(options);`

See https://framework7.io/docs/router-api.html

However, since this demo is based on Angular 1.x I cannot recommend to use it any more.

If you like Angular, then I recommend to use Ionic since it fully supports Angular2.

If you want to use Framework7, then use [Framework7-Vue](http://framework7.io/vue) or [Framework7-React](http://framework7.io/react).

**Comment by nutanlade** [comment]
@valnub 2 days back I started implementing using Ionic along with Angular2. After resolving router issue in Framework7 facing another issue where all controller constructor's are initializing when app is started. So didn't found any solution to resolve. That't why left Framework7 and started implementing Ionic. 

Thanks for your valuable time.
